server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses: [ INTERNAL_SERVER_ERROR ]
                methods: [ GET ]