create schema if not exists "comments_service";
SET SCHEMA 'comments_service';

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id  BIGINT,
    author_id BIGINT,
    message   VARCHAR(255)
);