create schema if not exists "requests_service";
SET SCHEMA 'requests_service';

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT       NOT NULL,
    event_id     BIGINT       NOT NULL,
    created_on   TIMESTAMP    NOT NULL,
    status       VARCHAR(100) NOT NULL
);
