create schema if not exists "stats_service";
SET SCHEMA 'stats_service';

CREATE TABLE IF NOT EXISTS event_similarity_score
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_A_id    BIGINT,
    event_B_id    BIGINT,
    score         DOUBLE PRECISION,
    calculated_at TIMESTAMP,
    UNIQUE (event_A_id, event_B_id)
);
