create schema if not exists "aggregator_service";
SET SCHEMA 'aggregator_service';

CREATE TABLE IF NOT EXISTS user_action
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    event_id        BIGINT NOT NULL,
    score         DOUBLE PRECISION NOT NULL,
    action_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS event_similarity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_A_id        BIGINT,
    event_B_id        BIGINT,
    s_min         DOUBLE PRECISION,
    s_a         DOUBLE PRECISION,
    s_b         DOUBLE PRECISION,
    calculated_at TIMESTAMP,
    created_at TIMESTAMP,
    UNIQUE (event_A_id, event_B_id)
);
